# Generated by Django 3.1.1 on 2020-09-24 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo_title', models.CharField(max_length=30)),
                ('todo_text', models.CharField(max_length=200)),
                ('todo_date', models.DateTimeField(verbose_name='date added')),
            ],
        ),
        migrations.CreateModel(
            name='Subtodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtodo_text', models.CharField(max_length=100)),
                ('subtodo_date', models.DateTimeField(verbose_name='date subtodo added')),
                ('subtodo_completed', models.BooleanField(default=False)),
                ('todo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todos.todo')),
            ],
        ),
    ]
