# Generated by Django 3.1.1 on 2020-09-25 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='todo_completed',
            field=models.BooleanField(default=False),
        ),
    ]
